sudo: required
dist: trusty
language: generic
before_install:
- sudo apt-get -qq update
- git clone https://github.com/cryptofuture/install-tl-ubuntu.git
- cd install-tl-ubuntu
- sudo ./install-tl-ubuntu
- eval "$(sed 's/^/export /' /etc/environment)"
- cd ..
script:
- xelatex -interaction=nonstopmode -halt-on-error notes.tex
- xelatex -interaction=nonstopmode -halt-on-error notes.tex
- xelatex -interaction=nonstopmode -halt-on-error notes.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN	# defined in travis dashboard
  target_branch: gh-pages
  on:
    branch: master

notifications:
  email: false
