sudo: required
dist: trusty
language: generic
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- xelatex -interaction=nonstopmode -halt-on-error notes.tex
- xelatex -interaction=nonstopmode -halt-on-error notes.tex

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN	# defined in travis dashboard
  target_branch: gh-pages
  on:
    branch: master
