sudo: required
dist: trusty
language: generic
before_install:
- sudo apt-get -qq update
- git clone https://github.com/cryptofuture/install-tl-ubuntu.git
- cd install-tl-ubuntu
- sudo ./install-tl-ubuntu
- eval "$(sed 's/^/export /' /etc/environment)"
- cd ..
- sudo apt-get -qq install biber
script:
- mkdir github-pages
- chmod +x make
- ./make
- mv notes.pdf github-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN	# defined in travis dashboard
  target_branch: gh-pages
  local_dir: github-pages
  on:
    branch: master

notifications:
  email: false
